/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AvailableTagsResponse,
  Bf2042AvailableTagsBf2042AvailabletagsGetParams,
  Bf2042CollectionsBf2042ScheduledcollectionsGetParams,
  Bf2042DetailedServerInfo,
  Bf2042GameStatus,
  Bf2042GetFeslidBf2042FeslidGetParams,
  Bf2042MixInfoBf2042MixinfoGetParams,
  Bf2042OffersBf2042OffersGetParams,
  Bf2042PlayerSearch,
  Bf2042PlaygroundBf2042PlaygroundGetParams,
  Bf2042PostFeslidBf2042FeslidPostBody,
  Bf2042Search,
  Bf2042blueprintsBf2042ScheduledblueprintGetParams,
  Bf2042detailedServersBf2042DetailedserverGetParams,
  Bf2042inventoryBf2042InventoryGetParams,
  Bf2042multipleBf2042MultiplePostParams,
  Bf2042playerBf2042PlayerGetParams,
  Bf2042serversBf2042ServersGetParams,
  Bf2042statsBf2042StatsGetParams,
  Bf2042translationsBf2042TranslationsGetParams,
  ConstraintsResponse,
  FeslPlayerInfo,
  GetMixesByIdResponse,
  GetOffersResponse,
  GetProgressionTypesResponse,
  GetStoreCatalogResponse,
  HTTPValidationError,
  LoggedServerDataBf2042ServerarrayGetParams,
  PlayerInfo,
  PlaygroundInfo,
  PrintLoggedDataBf2042StatusarrayGetParams,
  ScheduledBlueprintResponse,
  ScheduledCollectionsResponse,
  StatsArray,
  StatsarrayBf2042StatsarrayGetParams,
  StatusArray,
  TranslationsResponse
} from '.././model'



/**
 * You can choose to only send the playername and optional platform (defaults to pc)

or send if (playerId) nucleus_id and platform to skip name conversion
 * @summary Get stats from the given player for bf2042
 */
export const bf2042statsBf2042StatsGet = (
    params?: Bf2042statsBf2042StatsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/stats/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042statsBf2042StatsGetQueryKey = (params?: Bf2042statsBf2042StatsGetParams,) => {
    return [`https://api.gametools.network/bf2042/stats/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042statsBf2042StatsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042statsBf2042StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042statsBf2042StatsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>> = ({ signal }) => bf2042statsBf2042StatsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042statsBf2042StatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>>
export type Bf2042statsBf2042StatsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get stats from the given player for bf2042
 */
export const useBf2042statsBf2042StatsGet = <TData = Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042statsBf2042StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042statsBf2042StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042statsBf2042StatsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Send a list of players in a array where you want stats from
 * @summary Get for multiple players via grpc (max 128 players at a time)
 */
export const bf2042multipleBf2042MultiplePost = (
    playerInfo: PlayerInfo[],
    params?: Bf2042multipleBf2042MultiplePostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.post(
      `https://api.gametools.network/bf2042/multiple/`,
      playerInfo,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getBf2042multipleBf2042MultiplePostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf2042multipleBf2042MultiplePost>>, TError,{data: PlayerInfo[];params?: Bf2042multipleBf2042MultiplePostParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bf2042multipleBf2042MultiplePost>>, TError,{data: PlayerInfo[];params?: Bf2042multipleBf2042MultiplePostParams}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bf2042multipleBf2042MultiplePost>>, {data: PlayerInfo[];params?: Bf2042multipleBf2042MultiplePostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  bf2042multipleBf2042MultiplePost(data,params,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type Bf2042multipleBf2042MultiplePostMutationResult = NonNullable<Awaited<ReturnType<typeof bf2042multipleBf2042MultiplePost>>>
    export type Bf2042multipleBf2042MultiplePostMutationBody = PlayerInfo[]
    export type Bf2042multipleBf2042MultiplePostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Get for multiple players via grpc (max 128 players at a time)
 */
export const useBf2042multipleBf2042MultiplePost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf2042multipleBf2042MultiplePost>>, TError,{data: PlayerInfo[];params?: Bf2042multipleBf2042MultiplePostParams}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getBf2042multipleBf2042MultiplePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * To get multiple maps or regions, seperate them in a list with ';'.(cache of 10 seconds)
 * @summary Get a list of servers from portal based on given name
 */
export const bf2042serversBf2042ServersGet = (
    params?: Bf2042serversBf2042ServersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf2042Search>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/servers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042serversBf2042ServersGetQueryKey = (params?: Bf2042serversBf2042ServersGetParams,) => {
    return [`https://api.gametools.network/bf2042/servers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042serversBf2042ServersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042serversBf2042ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042serversBf2042ServersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>> = ({ signal }) => bf2042serversBf2042ServersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042serversBf2042ServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>>
export type Bf2042serversBf2042ServersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers from portal based on given name
 */
export const useBf2042serversBf2042ServersGet = <TData = Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042serversBf2042ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042serversBf2042ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042serversBf2042ServersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Returns username and avatar based on the given info
 * @summary Ask for the info about the username/avatar seperately
 */
export const bf2042PostFeslidBf2042FeslidPost = (
    bf2042PostFeslidBf2042FeslidPostBody: Bf2042PostFeslidBf2042FeslidPostBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FeslPlayerInfo>> => {
    
    return axios.post(
      `https://api.gametools.network/bf2042/feslid/`,
      bf2042PostFeslidBf2042FeslidPostBody,options
    );
  }



export const getBf2042PostFeslidBf2042FeslidPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf2042PostFeslidBf2042FeslidPost>>, TError,{data: Bf2042PostFeslidBf2042FeslidPostBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bf2042PostFeslidBf2042FeslidPost>>, TError,{data: Bf2042PostFeslidBf2042FeslidPostBody}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bf2042PostFeslidBf2042FeslidPost>>, {data: Bf2042PostFeslidBf2042FeslidPostBody}> = (props) => {
          const {data} = props ?? {};

          return  bf2042PostFeslidBf2042FeslidPost(data,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type Bf2042PostFeslidBf2042FeslidPostMutationResult = NonNullable<Awaited<ReturnType<typeof bf2042PostFeslidBf2042FeslidPost>>>
    export type Bf2042PostFeslidBf2042FeslidPostMutationBody = Bf2042PostFeslidBf2042FeslidPostBody
    export type Bf2042PostFeslidBf2042FeslidPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Ask for the info about the username/avatar seperately
 */
export const useBf2042PostFeslidBf2042FeslidPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf2042PostFeslidBf2042FeslidPost>>, TError,{data: Bf2042PostFeslidBf2042FeslidPostBody}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getBf2042PostFeslidBf2042FeslidPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns username and avatar based on the given info (get request for CORS)
 * @summary Ask for the info about the username/avatar seperately (get request for CORS)
 */
export const bf2042GetFeslidBf2042FeslidGet = (
    params?: Bf2042GetFeslidBf2042FeslidGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FeslPlayerInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/feslid/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042GetFeslidBf2042FeslidGetQueryKey = (params?: Bf2042GetFeslidBf2042FeslidGetParams,) => {
    return [`https://api.gametools.network/bf2042/feslid/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042GetFeslidBf2042FeslidGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042GetFeslidBf2042FeslidGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042GetFeslidBf2042FeslidGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>> = ({ signal }) => bf2042GetFeslidBf2042FeslidGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042GetFeslidBf2042FeslidGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>>
export type Bf2042GetFeslidBf2042FeslidGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Ask for the info about the username/avatar seperately (get request for CORS)
 */
export const useBf2042GetFeslidBf2042FeslidGet = <TData = Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042GetFeslidBf2042FeslidGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetFeslidBf2042FeslidGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042GetFeslidBf2042FeslidGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Available langauges for 'lang': ar-sa, de-de, en-us, es-es, es-mx, fr-fr, it-it, ja-jp, ko-kr, pl-pl, ru-ru, zh-cn and zh-tw. It defaults to en-us.
 * @summary Get a list of servers from portal based on given name
 */
export const bf2042detailedServersBf2042DetailedserverGet = (
    params?: Bf2042detailedServersBf2042DetailedserverGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf2042DetailedServerInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/detailedserver/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042detailedServersBf2042DetailedserverGetQueryKey = (params?: Bf2042detailedServersBf2042DetailedserverGetParams,) => {
    return [`https://api.gametools.network/bf2042/detailedserver/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042detailedServersBf2042DetailedserverGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042detailedServersBf2042DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042detailedServersBf2042DetailedserverGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>> = ({ signal }) => bf2042detailedServersBf2042DetailedserverGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042detailedServersBf2042DetailedserverGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>>
export type Bf2042detailedServersBf2042DetailedserverGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers from portal based on given name
 */
export const useBf2042detailedServersBf2042DetailedserverGet = <TData = Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042detailedServersBf2042DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042detailedServersBf2042DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042detailedServersBf2042DetailedserverGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get id of a player within bf2042
 */
export const bf2042playerBf2042PlayerGet = (
    params: Bf2042playerBf2042PlayerGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf2042PlayerSearch>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/player/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042playerBf2042PlayerGetQueryKey = (params: Bf2042playerBf2042PlayerGetParams,) => {
    return [`https://api.gametools.network/bf2042/player/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042playerBf2042PlayerGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>, TError = AxiosError<HTTPValidationError>>(params: Bf2042playerBf2042PlayerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042playerBf2042PlayerGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>> = ({ signal }) => bf2042playerBf2042PlayerGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042playerBf2042PlayerGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>>
export type Bf2042playerBf2042PlayerGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get id of a player within bf2042
 */
export const useBf2042playerBf2042PlayerGet = <TData = Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bf2042playerBf2042PlayerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042playerBf2042PlayerGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042playerBf2042PlayerGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary playercard info, no info added about it yet
 */
export const bf2042inventoryBf2042InventoryGet = (
    params?: Bf2042inventoryBf2042InventoryGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/inventory/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042inventoryBf2042InventoryGetQueryKey = (params?: Bf2042inventoryBf2042InventoryGetParams,) => {
    return [`https://api.gametools.network/bf2042/inventory/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042inventoryBf2042InventoryGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042inventoryBf2042InventoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042inventoryBf2042InventoryGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>> = ({ signal }) => bf2042inventoryBf2042InventoryGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042inventoryBf2042InventoryGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>>
export type Bf2042inventoryBf2042InventoryGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary playercard info, no info added about it yet
 */
export const useBf2042inventoryBf2042InventoryGet = <TData = Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042inventoryBf2042InventoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042inventoryBf2042InventoryGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042inventoryBf2042InventoryGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary translation files used for portal and serveritems (warning: a lot of data)
 */
export const bf2042translationsBf2042TranslationsGet = (
    params?: Bf2042translationsBf2042TranslationsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TranslationsResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/translations/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042translationsBf2042TranslationsGetQueryKey = (params?: Bf2042translationsBf2042TranslationsGetParams,) => {
    return [`https://api.gametools.network/bf2042/translations/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042translationsBf2042TranslationsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042translationsBf2042TranslationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042translationsBf2042TranslationsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>> = ({ signal }) => bf2042translationsBf2042TranslationsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042translationsBf2042TranslationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>>
export type Bf2042translationsBf2042TranslationsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary translation files used for portal and serveritems (warning: a lot of data)
 */
export const useBf2042translationsBf2042TranslationsGet = <TData = Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042translationsBf2042TranslationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042translationsBf2042TranslationsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042translationsBf2042TranslationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary all currently available portal settings (warning: a lot of data)
 */
export const bf2042blueprintsBf2042ScheduledblueprintGet = (
    params?: Bf2042blueprintsBf2042ScheduledblueprintGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ScheduledBlueprintResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/scheduledblueprint/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042blueprintsBf2042ScheduledblueprintGetQueryKey = (params?: Bf2042blueprintsBf2042ScheduledblueprintGetParams,) => {
    return [`https://api.gametools.network/bf2042/scheduledblueprint/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042blueprintsBf2042ScheduledblueprintGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042blueprintsBf2042ScheduledblueprintGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042blueprintsBf2042ScheduledblueprintGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>> = ({ signal }) => bf2042blueprintsBf2042ScheduledblueprintGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042blueprintsBf2042ScheduledblueprintGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>>
export type Bf2042blueprintsBf2042ScheduledblueprintGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary all currently available portal settings (warning: a lot of data)
 */
export const useBf2042blueprintsBf2042ScheduledblueprintGet = <TData = Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042blueprintsBf2042ScheduledblueprintGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042blueprintsBf2042ScheduledblueprintGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042blueprintsBf2042ScheduledblueprintGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary get list of available server/experience tags
 */
export const bf2042AvailableTagsBf2042AvailabletagsGet = (
    params?: Bf2042AvailableTagsBf2042AvailabletagsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AvailableTagsResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/availabletags/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042AvailableTagsBf2042AvailabletagsGetQueryKey = (params?: Bf2042AvailableTagsBf2042AvailabletagsGetParams,) => {
    return [`https://api.gametools.network/bf2042/availabletags/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042AvailableTagsBf2042AvailabletagsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042AvailableTagsBf2042AvailabletagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042AvailableTagsBf2042AvailabletagsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>> = ({ signal }) => bf2042AvailableTagsBf2042AvailabletagsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042AvailableTagsBf2042AvailabletagsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>>
export type Bf2042AvailableTagsBf2042AvailabletagsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary get list of available server/experience tags
 */
export const useBf2042AvailableTagsBf2042AvailabletagsGet = <TData = Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042AvailableTagsBf2042AvailabletagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042AvailableTagsBf2042AvailabletagsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042AvailableTagsBf2042AvailabletagsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary get the global limits for portal
 */
export const bf2042constraintsBf2042ConstraintsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConstraintsResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/constraints/`,options
    );
  }


export const getBf2042constraintsBf2042ConstraintsGetQueryKey = () => {
    return [`https://api.gametools.network/bf2042/constraints/`] as const;
    }

    
export const getBf2042constraintsBf2042ConstraintsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042constraintsBf2042ConstraintsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>> = ({ signal }) => bf2042constraintsBf2042ConstraintsGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042constraintsBf2042ConstraintsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>>
export type Bf2042constraintsBf2042ConstraintsGetQueryError = AxiosError<unknown>

/**
 * @summary get the global limits for portal
 */
export const useBf2042constraintsBf2042ConstraintsGet = <TData = Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042constraintsBf2042ConstraintsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042constraintsBf2042ConstraintsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary All current menuitems of the game
 */
export const bf2042CollectionsBf2042ScheduledcollectionsGet = (
    params?: Bf2042CollectionsBf2042ScheduledcollectionsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ScheduledCollectionsResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/scheduledcollections/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042CollectionsBf2042ScheduledcollectionsGetQueryKey = (params?: Bf2042CollectionsBf2042ScheduledcollectionsGetParams,) => {
    return [`https://api.gametools.network/bf2042/scheduledcollections/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042CollectionsBf2042ScheduledcollectionsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042CollectionsBf2042ScheduledcollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042CollectionsBf2042ScheduledcollectionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>> = ({ signal }) => bf2042CollectionsBf2042ScheduledcollectionsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042CollectionsBf2042ScheduledcollectionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>>
export type Bf2042CollectionsBf2042ScheduledcollectionsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary All current menuitems of the game
 */
export const useBf2042CollectionsBf2042ScheduledcollectionsGet = <TData = Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042CollectionsBf2042ScheduledcollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042CollectionsBf2042ScheduledcollectionsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042CollectionsBf2042ScheduledcollectionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get info about a submenu entry (via mixId)
 */
export const bf2042MixInfoBf2042MixinfoGet = (
    params: Bf2042MixInfoBf2042MixinfoGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetMixesByIdResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/mixinfo/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042MixInfoBf2042MixinfoGetQueryKey = (params: Bf2042MixInfoBf2042MixinfoGetParams,) => {
    return [`https://api.gametools.network/bf2042/mixinfo/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042MixInfoBf2042MixinfoGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>, TError = AxiosError<HTTPValidationError>>(params: Bf2042MixInfoBf2042MixinfoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042MixInfoBf2042MixinfoGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>> = ({ signal }) => bf2042MixInfoBf2042MixinfoGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042MixInfoBf2042MixinfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>>
export type Bf2042MixInfoBf2042MixinfoGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get info about a submenu entry (via mixId)
 */
export const useBf2042MixInfoBf2042MixinfoGet = <TData = Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bf2042MixInfoBf2042MixinfoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042MixInfoBf2042MixinfoGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042MixInfoBf2042MixinfoGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Gets some basic info about a experience made in portal
 */
export const bf2042PlaygroundBf2042PlaygroundGet = (
    params?: Bf2042PlaygroundBf2042PlaygroundGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlaygroundInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/playground/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042PlaygroundBf2042PlaygroundGetQueryKey = (params?: Bf2042PlaygroundBf2042PlaygroundGetParams,) => {
    return [`https://api.gametools.network/bf2042/playground/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042PlaygroundBf2042PlaygroundGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042PlaygroundBf2042PlaygroundGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042PlaygroundBf2042PlaygroundGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>> = ({ signal }) => bf2042PlaygroundBf2042PlaygroundGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042PlaygroundBf2042PlaygroundGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>>
export type Bf2042PlaygroundBf2042PlaygroundGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Gets some basic info about a experience made in portal
 */
export const useBf2042PlaygroundBf2042PlaygroundGet = <TData = Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042PlaygroundBf2042PlaygroundGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042PlaygroundBf2042PlaygroundGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042PlaygroundBf2042PlaygroundGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get list of dlc's that can be bought
 */
export const bf2042GetStoreCatalogBf2042StorecatalogGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetStoreCatalogResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/storecatalog/`,options
    );
  }


export const getBf2042GetStoreCatalogBf2042StorecatalogGetQueryKey = () => {
    return [`https://api.gametools.network/bf2042/storecatalog/`] as const;
    }

    
export const getBf2042GetStoreCatalogBf2042StorecatalogGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042GetStoreCatalogBf2042StorecatalogGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>> = ({ signal }) => bf2042GetStoreCatalogBf2042StorecatalogGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042GetStoreCatalogBf2042StorecatalogGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>>
export type Bf2042GetStoreCatalogBf2042StorecatalogGetQueryError = AxiosError<unknown>

/**
 * @summary Get list of dlc's that can be bought
 */
export const useBf2042GetStoreCatalogBf2042StorecatalogGet = <TData = Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetStoreCatalogBf2042StorecatalogGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042GetStoreCatalogBf2042StorecatalogGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the offers available in the store  (warning: a lot of data)
 */
export const bf2042OffersBf2042OffersGet = (
    params?: Bf2042OffersBf2042OffersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetOffersResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/offers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf2042OffersBf2042OffersGetQueryKey = (params?: Bf2042OffersBf2042OffersGetParams,) => {
    return [`https://api.gametools.network/bf2042/offers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf2042OffersBf2042OffersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf2042OffersBf2042OffersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042OffersBf2042OffersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>> = ({ signal }) => bf2042OffersBf2042OffersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042OffersBf2042OffersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>>
export type Bf2042OffersBf2042OffersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the offers available in the store  (warning: a lot of data)
 */
export const useBf2042OffersBf2042OffersGet = <TData = Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf2042OffersBf2042OffersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042OffersBf2042OffersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042OffersBf2042OffersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the available progression types for Portal
 */
export const bf2042GetProgressionTypesBf2042ProgressiontypesGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetProgressionTypesResponse>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/progressiontypes/`,options
    );
  }


export const getBf2042GetProgressionTypesBf2042ProgressiontypesGetQueryKey = () => {
    return [`https://api.gametools.network/bf2042/progressiontypes/`] as const;
    }

    
export const getBf2042GetProgressionTypesBf2042ProgressiontypesGetQueryOptions = <TData = Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf2042GetProgressionTypesBf2042ProgressiontypesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>> = ({ signal }) => bf2042GetProgressionTypesBf2042ProgressiontypesGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf2042GetProgressionTypesBf2042ProgressiontypesGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>>
export type Bf2042GetProgressionTypesBf2042ProgressiontypesGetQueryError = AxiosError<unknown>

/**
 * @summary Get the available progression types for Portal
 */
export const useBf2042GetProgressionTypesBf2042ProgressiontypesGet = <TData = Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf2042GetProgressionTypesBf2042ProgressiontypesGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf2042GetProgressionTypesBf2042ProgressiontypesGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const statsarrayBf2042StatsarrayGet = (
    params?: StatsarrayBf2042StatsarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatsArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/statsarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatsarrayBf2042StatsarrayGetQueryKey = (params?: StatsarrayBf2042StatsarrayGetParams,) => {
    return [`https://api.gametools.network/bf2042/statsarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatsarrayBf2042StatsarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatsarrayBf2042StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsarrayBf2042StatsarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>> = ({ signal }) => statsarrayBf2042StatsarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsarrayBf2042StatsarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>>
export type StatsarrayBf2042StatsarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const useStatsarrayBf2042StatsarrayGet = <TData = Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatsarrayBf2042StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf2042StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsarrayBf2042StatsarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour for Battlefield 2042 portal.
 */
export const printLoggedDataBf2042StatusarrayGet = (
    params?: PrintLoggedDataBf2042StatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBf2042StatusarrayGetQueryKey = (params?: PrintLoggedDataBf2042StatusarrayGetParams,) => {
    return [`https://api.gametools.network/bf2042/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBf2042StatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBf2042StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBf2042StatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>> = ({ signal }) => printLoggedDataBf2042StatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBf2042StatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>>
export type PrintLoggedDataBf2042StatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour for Battlefield 2042 portal.
 */
export const usePrintLoggedDataBf2042StatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBf2042StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf2042StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBf2042StatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the servers playeramount over time
 */
export const loggedServerDataBf2042ServerarrayGet = (
    params?: LoggedServerDataBf2042ServerarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/serverarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLoggedServerDataBf2042ServerarrayGetQueryKey = (params?: LoggedServerDataBf2042ServerarrayGetParams,) => {
    return [`https://api.gametools.network/bf2042/serverarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getLoggedServerDataBf2042ServerarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: LoggedServerDataBf2042ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoggedServerDataBf2042ServerarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>> = ({ signal }) => loggedServerDataBf2042ServerarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LoggedServerDataBf2042ServerarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>>
export type LoggedServerDataBf2042ServerarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the servers playeramount over time
 */
export const useLoggedServerDataBf2042ServerarrayGet = <TData = Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: LoggedServerDataBf2042ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf2042ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLoggedServerDataBf2042ServerarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions for Battlefield 2042 portal.
 */
export const gameStatusBf2042StatusGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf2042GameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bf2042/status/`,options
    );
  }


export const getGameStatusBf2042StatusGetQueryKey = () => {
    return [`https://api.gametools.network/bf2042/status/`] as const;
    }

    
export const getGameStatusBf2042StatusGetQueryOptions = <TData = Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGameStatusBf2042StatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>> = ({ signal }) => gameStatusBf2042StatusGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GameStatusBf2042StatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>>
export type GameStatusBf2042StatusGetQueryError = AxiosError<unknown>

/**
 * @summary Get the player- / serveramount for all regions for Battlefield 2042 portal.
 */
export const useGameStatusBf2042StatusGet = <TData = Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameStatusBf2042StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGameStatusBf2042StatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



