/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CheckbanManagerCheckbanGetParams,
  HTTPValidationError,
  LeaderboardManagerLeaderboardGetParams,
  LiveManagerLiveGetParams,
  ManagerInfo,
  ManagerLivePlayer,
  ManagerPlayerSession,
  ManagerServerLeaderBoard,
  ManagerServerPlayers,
  PlayersManagerPlayersGetParams,
  SessionsManagerSessionsGetParams
} from '.././model'



/**
 * This is only the amount of usage for privacy
 * @summary Get usage info about the manager.
 */
export const infoManagerInfoGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManagerInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/info/`,options
    );
  }


export const getInfoManagerInfoGetQueryKey = () => {
    return [`https://api.gametools.network/manager/info/`] as const;
    }

    
export const getInfoManagerInfoGetQueryOptions = <TData = Awaited<ReturnType<typeof infoManagerInfoGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infoManagerInfoGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInfoManagerInfoGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof infoManagerInfoGet>>> = ({ signal }) => infoManagerInfoGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof infoManagerInfoGet>>, TError, TData> & { queryKey: QueryKey }
}

export type InfoManagerInfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof infoManagerInfoGet>>>
export type InfoManagerInfoGetQueryError = AxiosError<unknown>

/**
 * @summary Get usage info about the manager.
 */
export const useInfoManagerInfoGet = <TData = Awaited<ReturnType<typeof infoManagerInfoGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infoManagerInfoGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getInfoManagerInfoGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * It only tracks the session within this week and only works on servers using our manager: manager.gametools.network
 * @summary Get the most recent stats from a player of our manager.
 */
export const sessionsManagerSessionsGet = (
    params?: SessionsManagerSessionsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManagerPlayerSession>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/sessions/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getSessionsManagerSessionsGetQueryKey = (params?: SessionsManagerSessionsGetParams,) => {
    return [`https://api.gametools.network/manager/sessions/`, ...(params ? [params]: [])] as const;
    }

    
export const getSessionsManagerSessionsGetQueryOptions = <TData = Awaited<ReturnType<typeof sessionsManagerSessionsGet>>, TError = AxiosError<HTTPValidationError>>(params?: SessionsManagerSessionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsManagerSessionsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionsManagerSessionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionsManagerSessionsGet>>> = ({ signal }) => sessionsManagerSessionsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionsManagerSessionsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type SessionsManagerSessionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof sessionsManagerSessionsGet>>>
export type SessionsManagerSessionsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the most recent stats from a player of our manager.
 */
export const useSessionsManagerSessionsGet = <TData = Awaited<ReturnType<typeof sessionsManagerSessionsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: SessionsManagerSessionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsManagerSessionsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getSessionsManagerSessionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * It only works on servers using our manager: manager.gametools.network
 * @summary Get the live stats difference since the player joined a server, stats: none means couldn't find stats
 */
export const liveManagerLiveGet = (
    params?: LiveManagerLiveGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManagerLivePlayer>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/live/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLiveManagerLiveGetQueryKey = (params?: LiveManagerLiveGetParams,) => {
    return [`https://api.gametools.network/manager/live/`, ...(params ? [params]: [])] as const;
    }

    
export const getLiveManagerLiveGetQueryOptions = <TData = Awaited<ReturnType<typeof liveManagerLiveGet>>, TError = AxiosError<HTTPValidationError>>(params?: LiveManagerLiveGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveManagerLiveGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLiveManagerLiveGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof liveManagerLiveGet>>> = ({ signal }) => liveManagerLiveGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof liveManagerLiveGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LiveManagerLiveGetQueryResult = NonNullable<Awaited<ReturnType<typeof liveManagerLiveGet>>>
export type LiveManagerLiveGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the live stats difference since the player joined a server, stats: none means couldn't find stats
 */
export const useLiveManagerLiveGet = <TData = Awaited<ReturnType<typeof liveManagerLiveGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: LiveManagerLiveGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liveManagerLiveGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLiveManagerLiveGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * It only works on servers using our manager: manager.gametools.network
 * @summary Get playerlist of your server
 */
export const playersManagerPlayersGet = (
    params?: PlayersManagerPlayersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManagerServerPlayers>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/players/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPlayersManagerPlayersGetQueryKey = (params?: PlayersManagerPlayersGetParams,) => {
    return [`https://api.gametools.network/manager/players/`, ...(params ? [params]: [])] as const;
    }

    
export const getPlayersManagerPlayersGetQueryOptions = <TData = Awaited<ReturnType<typeof playersManagerPlayersGet>>, TError = AxiosError<HTTPValidationError>>(params?: PlayersManagerPlayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playersManagerPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlayersManagerPlayersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof playersManagerPlayersGet>>> = ({ signal }) => playersManagerPlayersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof playersManagerPlayersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PlayersManagerPlayersGetQueryResult = NonNullable<Awaited<ReturnType<typeof playersManagerPlayersGet>>>
export type PlayersManagerPlayersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get playerlist of your server
 */
export const usePlayersManagerPlayersGet = <TData = Awaited<ReturnType<typeof playersManagerPlayersGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PlayersManagerPlayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playersManagerPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPlayersManagerPlayersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * It only works on servers using our manager: manager.gametools.network
 * @summary Get best players of your server
 */
export const leaderboardManagerLeaderboardGet = (
    params?: LeaderboardManagerLeaderboardGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManagerServerLeaderBoard>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/leaderboard/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLeaderboardManagerLeaderboardGetQueryKey = (params?: LeaderboardManagerLeaderboardGetParams,) => {
    return [`https://api.gametools.network/manager/leaderboard/`, ...(params ? [params]: [])] as const;
    }

    
export const getLeaderboardManagerLeaderboardGetQueryOptions = <TData = Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>, TError = AxiosError<HTTPValidationError>>(params?: LeaderboardManagerLeaderboardGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLeaderboardManagerLeaderboardGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>> = ({ signal }) => leaderboardManagerLeaderboardGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LeaderboardManagerLeaderboardGetQueryResult = NonNullable<Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>>
export type LeaderboardManagerLeaderboardGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get best players of your server
 */
export const useLeaderboardManagerLeaderboardGet = <TData = Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: LeaderboardManagerLeaderboardGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof leaderboardManagerLeaderboardGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLeaderboardManagerLeaderboardGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Check if a player is already banned in a server within the manager if the group has made his bans public
 */
export const checkbanManagerCheckbanGet = (
    params?: CheckbanManagerCheckbanGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/manager/checkban/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getCheckbanManagerCheckbanGetQueryKey = (params?: CheckbanManagerCheckbanGetParams,) => {
    return [`https://api.gametools.network/manager/checkban/`, ...(params ? [params]: [])] as const;
    }

    
export const getCheckbanManagerCheckbanGetQueryOptions = <TData = Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>, TError = AxiosError<HTTPValidationError>>(params?: CheckbanManagerCheckbanGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckbanManagerCheckbanGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>> = ({ signal }) => checkbanManagerCheckbanGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>, TError, TData> & { queryKey: QueryKey }
}

export type CheckbanManagerCheckbanGetQueryResult = NonNullable<Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>>
export type CheckbanManagerCheckbanGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Check if a player is already banned in a server within the manager if the group has made his bans public
 */
export const useCheckbanManagerCheckbanGet = <TData = Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: CheckbanManagerCheckbanGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkbanManagerCheckbanGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getCheckbanManagerCheckbanGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



