/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Bfbc2serversBfvietnamServersGetParams,
  BfvietnamstatusBfvietnamStatusGetParams,
  HTTPValidationError,
  LoggedServerDataBfvietnamServerarrayGetParams,
  OlderGameStatus,
  OlderTitleSearch,
  PrintLoggedDataBfvietnamStatusarrayGetParams,
  StatusArray
} from '.././model'



/**
 * @summary Get a list of servers based on given name or ip:port
 */
export const bfbc2serversBfvietnamServersGet = (
    params: Bfbc2serversBfvietnamServersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OlderTitleSearch>> => {
    
    return axios.get(
      `https://api.gametools.network/bfvietnam/servers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBfbc2serversBfvietnamServersGetQueryKey = (params: Bfbc2serversBfvietnamServersGetParams,) => {
    return [`https://api.gametools.network/bfvietnam/servers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBfbc2serversBfvietnamServersGetQueryOptions = <TData = Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>, TError = AxiosError<HTTPValidationError>>(params: Bfbc2serversBfvietnamServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBfbc2serversBfvietnamServersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>> = ({ signal }) => bfbc2serversBfvietnamServersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bfbc2serversBfvietnamServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>>
export type Bfbc2serversBfvietnamServersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers based on given name or ip:port
 */
export const useBfbc2serversBfvietnamServersGet = <TData = Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bfbc2serversBfvietnamServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfbc2serversBfvietnamServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBfbc2serversBfvietnamServersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const printLoggedDataBfvietnamStatusarrayGet = (
    params?: PrintLoggedDataBfvietnamStatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bfvietnam/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBfvietnamStatusarrayGetQueryKey = (params?: PrintLoggedDataBfvietnamStatusarrayGetParams,) => {
    return [`https://api.gametools.network/bfvietnam/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBfvietnamStatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBfvietnamStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBfvietnamStatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>> = ({ signal }) => printLoggedDataBfvietnamStatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBfvietnamStatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>>
export type PrintLoggedDataBfvietnamStatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const usePrintLoggedDataBfvietnamStatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBfvietnamStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfvietnamStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBfvietnamStatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the servers playeramount over time
 */
export const loggedServerDataBfvietnamServerarrayGet = (
    params: LoggedServerDataBfvietnamServerarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bfvietnam/serverarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLoggedServerDataBfvietnamServerarrayGetQueryKey = (params: LoggedServerDataBfvietnamServerarrayGetParams,) => {
    return [`https://api.gametools.network/bfvietnam/serverarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getLoggedServerDataBfvietnamServerarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(params: LoggedServerDataBfvietnamServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoggedServerDataBfvietnamServerarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>> = ({ signal }) => loggedServerDataBfvietnamServerarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LoggedServerDataBfvietnamServerarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>>
export type LoggedServerDataBfvietnamServerarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the servers playeramount over time
 */
export const useLoggedServerDataBfvietnamServerarrayGet = <TData = Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params: LoggedServerDataBfvietnamServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBfvietnamServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLoggedServerDataBfvietnamServerarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions.
 */
export const bfvietnamstatusBfvietnamStatusGet = (
    params?: BfvietnamstatusBfvietnamStatusGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OlderGameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bfvietnam/status/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBfvietnamstatusBfvietnamStatusGetQueryKey = (params?: BfvietnamstatusBfvietnamStatusGetParams,) => {
    return [`https://api.gametools.network/bfvietnam/status/`, ...(params ? [params]: [])] as const;
    }

    
export const getBfvietnamstatusBfvietnamStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>, TError = AxiosError<HTTPValidationError>>(params?: BfvietnamstatusBfvietnamStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBfvietnamstatusBfvietnamStatusGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>> = ({ signal }) => bfvietnamstatusBfvietnamStatusGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type BfvietnamstatusBfvietnamStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>>
export type BfvietnamstatusBfvietnamStatusGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions.
 */
export const useBfvietnamstatusBfvietnamStatusGet = <TData = Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: BfvietnamstatusBfvietnamStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfvietnamstatusBfvietnamStatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBfvietnamstatusBfvietnamStatusGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



