/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'



/**
 * @summary Get all banned player ids from bfeac (used internally, cached for 1 hour)
 */
export const getAllBannedPlayersBfeacBannedPlayersGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bfeac/banned_players`,options
    );
  }


export const getGetAllBannedPlayersBfeacBannedPlayersGetQueryKey = () => {
    return [`https://api.gametools.network/bfeac/banned_players`] as const;
    }

    
export const getGetAllBannedPlayersBfeacBannedPlayersGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBannedPlayersBfeacBannedPlayersGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>> = ({ signal }) => getAllBannedPlayersBfeacBannedPlayersGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllBannedPlayersBfeacBannedPlayersGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>>
export type GetAllBannedPlayersBfeacBannedPlayersGetQueryError = AxiosError<unknown>

/**
 * @summary Get all banned player ids from bfeac (used internally, cached for 1 hour)
 */
export const useGetAllBannedPlayersBfeacBannedPlayersGet = <TData = Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfeacBannedPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllBannedPlayersBfeacBannedPlayersGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



