/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BfBansCheckBfbanCheckbanPostBodyItem,
  GetBfBansCheckBfbanCheckbanGetParams,
  HTTPValidationError
} from '.././model'



/**
 * Give a list of names, userids and/or personaids seperated with ","
 this is a GET request because POST isn't allowed when allow_origins="*"
 * @summary check if list of player is banned in bfban
 */
export const getBfBansCheckBfbanCheckbanGet = (
    params?: GetBfBansCheckBfbanCheckbanGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bfban/checkban/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetBfBansCheckBfbanCheckbanGetQueryKey = (params?: GetBfBansCheckBfbanCheckbanGetParams,) => {
    return [`https://api.gametools.network/bfban/checkban/`, ...(params ? [params]: [])] as const;
    }

    
export const getGetBfBansCheckBfbanCheckbanGetQueryOptions = <TData = Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>, TError = AxiosError<HTTPValidationError>>(params?: GetBfBansCheckBfbanCheckbanGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBfBansCheckBfbanCheckbanGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>> = ({ signal }) => getBfBansCheckBfbanCheckbanGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBfBansCheckBfbanCheckbanGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>>
export type GetBfBansCheckBfbanCheckbanGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary check if list of player is banned in bfban
 */
export const useGetBfBansCheckBfbanCheckbanGet = <TData = Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: GetBfBansCheckBfbanCheckbanGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBfBansCheckBfbanCheckbanGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetBfBansCheckBfbanCheckbanGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary check if list of player is banned in bfban
 */
export const bfBansCheckBfbanCheckbanPost = (
    bfBansCheckBfbanCheckbanPostBodyItem: BfBansCheckBfbanCheckbanPostBodyItem[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.post(
      `https://api.gametools.network/bfban/checkban/`,
      bfBansCheckBfbanCheckbanPostBodyItem,options
    );
  }



export const getBfBansCheckBfbanCheckbanPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bfBansCheckBfbanCheckbanPost>>, TError,{data: BfBansCheckBfbanCheckbanPostBodyItem[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bfBansCheckBfbanCheckbanPost>>, TError,{data: BfBansCheckBfbanCheckbanPostBodyItem[]}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bfBansCheckBfbanCheckbanPost>>, {data: BfBansCheckBfbanCheckbanPostBodyItem[]}> = (props) => {
          const {data} = props ?? {};

          return  bfBansCheckBfbanCheckbanPost(data,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type BfBansCheckBfbanCheckbanPostMutationResult = NonNullable<Awaited<ReturnType<typeof bfBansCheckBfbanCheckbanPost>>>
    export type BfBansCheckBfbanCheckbanPostMutationBody = BfBansCheckBfbanCheckbanPostBodyItem[]
    export type BfBansCheckBfbanCheckbanPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary check if list of player is banned in bfban
 */
export const useBfBansCheckBfbanCheckbanPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bfBansCheckBfbanCheckbanPost>>, TError,{data: BfBansCheckBfbanCheckbanPostBodyItem[]}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getBfBansCheckBfbanCheckbanPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all banned players ids from bfban (used internally, cached for 1 hour)
 */
export const getAllBannedPlayersBfbanBannedPlayersGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bfban/banned_players/`,options
    );
  }


export const getGetAllBannedPlayersBfbanBannedPlayersGetQueryKey = () => {
    return [`https://api.gametools.network/bfban/banned_players/`] as const;
    }

    
export const getGetAllBannedPlayersBfbanBannedPlayersGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBannedPlayersBfbanBannedPlayersGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>> = ({ signal }) => getAllBannedPlayersBfbanBannedPlayersGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllBannedPlayersBfbanBannedPlayersGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>>
export type GetAllBannedPlayersBfbanBannedPlayersGetQueryError = AxiosError<unknown>

/**
 * @summary Get all banned players ids from bfban (used internally, cached for 1 hour)
 */
export const useGetAllBannedPlayersBfbanBannedPlayersGet = <TData = Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBannedPlayersBfbanBannedPlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllBannedPlayersBfbanBannedPlayersGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



