/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  Bf2ClassStats,
  Bf2Leaderboard,
  Bf2MainStats,
  Bf2VehicleStats,
  Bf2WeaponStats,
  OlderGameStatus,
  OlderTitleSearch,
  StatusArray
} from '.././model'

export const getBf2serversBf2ServersGetMock = (overrideResponse: any = {}): OlderTitleSearch => ({servers: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({ip: faker.word.sample(), map: faker.word.sample(), mapImage: faker.word.sample(), maxPlayers: faker.number.int({min: undefined, max: undefined}), mode: faker.word.sample(), playerAmount: faker.number.int({min: undefined, max: undefined}), port: faker.word.sample(), prefix: faker.word.sample(), serverLink: faker.word.sample(), smallMode: faker.word.sample(), ...overrideResponse})), ...overrideResponse})

export const getBf2statsBf2StatsGetMock = (overrideResponse: any = {}): Bf2MainStats => ({Accuracy: faker.word.sample(), Deaths: faker.number.int({min: undefined, max: undefined}), Kills: faker.number.int({min: undefined, max: undefined}), KPM: faker.number.int({min: undefined, max: undefined}), Loses: faker.number.int({min: undefined, max: undefined}), Rank: faker.word.sample(), SPM: faker.number.int({min: undefined, max: undefined}), Win: faker.word.sample(), Wins: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getBf2leaderboardBf2LeaderboardGetMock = (overrideResponse: any = {}): Bf2Leaderboard => ({players: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({countryCode: faker.word.sample(), id: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), rank: faker.number.int({min: undefined, max: undefined}), score: faker.number.int({min: undefined, max: undefined}), secondsPlayed: faker.number.int({min: undefined, max: undefined}), timePlayed: faker.word.sample(), ...overrideResponse})), ...overrideResponse})

export const getBf2weaponsBf2WeaponsGetMock = (overrideResponse: any = {}): Bf2WeaponStats => ({weapons: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({accuracy: faker.word.sample(), killDeath: faker.number.int({min: undefined, max: undefined}), kills: faker.number.int({min: undefined, max: undefined}), killsPerMinute: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), ...overrideResponse})), ...overrideResponse})

export const getBf2vehiclesBf2VehiclesGetMock = (overrideResponse: any = {}): Bf2VehicleStats => ({vehicles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({kills: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), ...overrideResponse})), ...overrideResponse})

export const getBf2classesBf2ClassesGetMock = (overrideResponse: any = {}): Bf2ClassStats => ({classes: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({killDeath: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), timeAsClass: faker.word.sample(), ...overrideResponse})), ...overrideResponse})

export const getBf2StatusBf2StatusGetMock = (overrideResponse: any = {}): OlderGameStatus => ({regions: {
        [faker.string.alphanumeric(5)]: {region: faker.word.sample(), serverAmount: faker.number.int({min: undefined, max: undefined}), soldierAmount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse}
      }, ...overrideResponse})

export const getBf2StatusArrayBf2StatusarrayGetMock = (overrideResponse: any = {}): StatusArray => ({endTime: faker.word.sample(), soldierAmount: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), startTime: faker.word.sample(), timeStamps: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), ...overrideResponse})


export const getBf2serversBf2ServersGetMockHandler = (overrideResponse?: OlderTitleSearch) => {
  return http.get('*/bf2/servers/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2serversBf2ServersGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2statsBf2StatsGetMockHandler = (overrideResponse?: Bf2MainStats) => {
  return http.get('*/bf2/stats/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2statsBf2StatsGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2leaderboardBf2LeaderboardGetMockHandler = (overrideResponse?: Bf2Leaderboard) => {
  return http.get('*/bf2/leaderboard/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2leaderboardBf2LeaderboardGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2weaponsBf2WeaponsGetMockHandler = (overrideResponse?: Bf2WeaponStats) => {
  return http.get('*/bf2/weapons/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2weaponsBf2WeaponsGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2vehiclesBf2VehiclesGetMockHandler = (overrideResponse?: Bf2VehicleStats) => {
  return http.get('*/bf2/vehicles/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2vehiclesBf2VehiclesGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2classesBf2ClassesGetMockHandler = (overrideResponse?: Bf2ClassStats) => {
  return http.get('*/bf2/classes/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2classesBf2ClassesGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2StatusBf2StatusGetMockHandler = (overrideResponse?: OlderGameStatus) => {
  return http.get('*/bf2/status/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2StatusBf2StatusGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getLoggedServerDataBf2ServerarrayGetMockHandler = () => {
  return http.get('*/bf2/serverarray/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getBf2StatusArrayBf2StatusarrayGetMockHandler = (overrideResponse?: StatusArray) => {
  return http.get('*/bf2/statusarray/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getBf2StatusArrayBf2StatusarrayGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getBattlefield2Mock = () => [
  getBf2serversBf2ServersGetMockHandler(),
  getBf2statsBf2StatsGetMockHandler(),
  getBf2leaderboardBf2LeaderboardGetMockHandler(),
  getBf2weaponsBf2WeaponsGetMockHandler(),
  getBf2vehiclesBf2VehiclesGetMockHandler(),
  getBf2classesBf2ClassesGetMockHandler(),
  getBf2StatusBf2StatusGetMockHandler(),
  getLoggedServerDataBf2ServerarrayGetMockHandler(),
  getBf2StatusArrayBf2StatusarrayGetMockHandler()
]
