/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Bf1AllBf1AllGetParams,
  Bf1Combined,
  Bf1DetailedServerInfo,
  Bf1SeederServerPlayers,
  Bf1ServerPlayers,
  Bf1classesBf1ClassesGetParams,
  Bf1detailedserversBf1DetailedserverGetParams,
  Bf1gamemodeBf1GamemodeGetParams,
  Bf1multipleBf1MultiplePostParams,
  Bf1playerBf1PlayerGetParams,
  Bf1playersBf1PlayersGetParams,
  Bf1progressBf1ProgressGetParams,
  Bf1seederplayersBf1SeederplayersGetParams,
  Bf1serversBf1ServersGetParams,
  Bf1statsBf1StatsGetParams,
  Bf1vehiclesBf1VehiclesGetParams,
  Bf1weaponsBf1WeaponsGetParams,
  FrostbiteClassStats,
  FrostbiteGameStatus,
  FrostbiteMainStats,
  FrostbiteSearch,
  FrostbiteStatusArray,
  FrostbiteVehicleStats,
  FrostbiteWeaponStats,
  GamemodeStats,
  HTTPValidationError,
  LoggedServerDataBf1ServerarrayGetParams,
  PersonaInfo,
  PrintLoggedDataBf1StatusarrayGetParams,
  ProgressStats,
  StatsArray,
  StatsarrayBf1StatsarrayGetParams,
  StatusBf1StatusGetParams
} from '.././model'



/**
 * ownerId == None, can't be gathered for bf1. used in bf5.
                    The regions available are: all (all regions), eu, asia, nam (north america), sam (south america), au (Australia) or oc (Oceana).
                    For platform there is pc, xboxone and ps4 (cache of 10 seconds)
                    For player filter you can use oneToFive, sixToTen, tenPlus or none, comma seperated list is also a option example: "&player_filters=onetofive,sixtoten" to filter on the amount of free slots.
                    Same for gamemode filter as with player filter but with the name of the gamemode
 * @summary Get a list of servers based on given name
 */
export const bf1serversBf1ServersGet = (
    params: Bf1serversBf1ServersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteSearch>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/servers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1serversBf1ServersGetQueryKey = (params: Bf1serversBf1ServersGetParams,) => {
    return [`https://api.gametools.network/bf1/servers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1serversBf1ServersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1serversBf1ServersGet>>, TError = AxiosError<HTTPValidationError>>(params: Bf1serversBf1ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1serversBf1ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1serversBf1ServersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1serversBf1ServersGet>>> = ({ signal }) => bf1serversBf1ServersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1serversBf1ServersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1serversBf1ServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1serversBf1ServersGet>>>
export type Bf1serversBf1ServersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers based on given name
 */
export const useBf1serversBf1ServersGet = <TData = Awaited<ReturnType<typeof bf1serversBf1ServersGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bf1serversBf1ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1serversBf1ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1serversBf1ServersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * For platform there is pc, xboxone and ps4 (cache of 10 seconds)
 * @summary Get detailed info about 1 server
 */
export const bf1detailedserversBf1DetailedserverGet = (
    params?: Bf1detailedserversBf1DetailedserverGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf1DetailedServerInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/detailedserver/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1detailedserversBf1DetailedserverGetQueryKey = (params?: Bf1detailedserversBf1DetailedserverGetParams,) => {
    return [`https://api.gametools.network/bf1/detailedserver/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1detailedserversBf1DetailedserverGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1detailedserversBf1DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1detailedserversBf1DetailedserverGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>> = ({ signal }) => bf1detailedserversBf1DetailedserverGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1detailedserversBf1DetailedserverGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>>
export type Bf1detailedserversBf1DetailedserverGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get detailed info about 1 server
 */
export const useBf1detailedserversBf1DetailedserverGet = <TData = Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1detailedserversBf1DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1detailedserversBf1DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1detailedserversBf1DetailedserverGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Send a list of player id's in a array where you want stats from (Only pc is supported)
 * @summary Get for multiple players via blaze (max 64 players at a time)
 */
export const bf1multipleBf1MultiplePost = (
    bf1multipleBf1MultiplePostBody: number[],
    params?: Bf1multipleBf1MultiplePostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.post(
      `https://api.gametools.network/bf1/multiple/`,
      bf1multipleBf1MultiplePostBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getBf1multipleBf1MultiplePostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf1multipleBf1MultiplePost>>, TError,{data: number[];params?: Bf1multipleBf1MultiplePostParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bf1multipleBf1MultiplePost>>, TError,{data: number[];params?: Bf1multipleBf1MultiplePostParams}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bf1multipleBf1MultiplePost>>, {data: number[];params?: Bf1multipleBf1MultiplePostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  bf1multipleBf1MultiplePost(data,params,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type Bf1multipleBf1MultiplePostMutationResult = NonNullable<Awaited<ReturnType<typeof bf1multipleBf1MultiplePost>>>
    export type Bf1multipleBf1MultiplePostMutationBody = number[]
    export type Bf1multipleBf1MultiplePostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Get for multiple players via blaze (max 64 players at a time)
 */
export const useBf1multipleBf1MultiplePost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bf1multipleBf1MultiplePost>>, TError,{data: number[];params?: Bf1multipleBf1MultiplePostParams}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getBf1multipleBf1MultiplePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary get a list of players of a given server, use "," between gameids to request multiple (when you request multiple you wont get platoon info of players, max 10 servers per server)
 */
export const bf1playersBf1PlayersGet = (
    params?: Bf1playersBf1PlayersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf1ServerPlayers>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/players/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1playersBf1PlayersGetQueryKey = (params?: Bf1playersBf1PlayersGetParams,) => {
    return [`https://api.gametools.network/bf1/players/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1playersBf1PlayersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1playersBf1PlayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1playersBf1PlayersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>> = ({ signal }) => bf1playersBf1PlayersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1playersBf1PlayersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>>
export type Bf1playersBf1PlayersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary get a list of players of a given server, use "," between gameids to request multiple (when you request multiple you wont get platoon info of players, max 10 servers per server)
 */
export const useBf1playersBf1PlayersGet = <TData = Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1playersBf1PlayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1playersBf1PlayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1playersBf1PlayersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This returns some extra info that can only be gathered from a real game session: score, kills and deaths.
            
Use the one above as backup, as it only returns when someone has a sender running
 * @summary get a list of players of a given server from the "playerlist sender.exe" or the seeding systems' automated message system.
 */
export const bf1seederplayersBf1SeederplayersGet = (
    params?: Bf1seederplayersBf1SeederplayersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf1SeederServerPlayers>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/seederplayers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1seederplayersBf1SeederplayersGetQueryKey = (params?: Bf1seederplayersBf1SeederplayersGetParams,) => {
    return [`https://api.gametools.network/bf1/seederplayers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1seederplayersBf1SeederplayersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1seederplayersBf1SeederplayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1seederplayersBf1SeederplayersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>> = ({ signal }) => bf1seederplayersBf1SeederplayersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1seederplayersBf1SeederplayersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>>
export type Bf1seederplayersBf1SeederplayersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary get a list of players of a given server from the "playerlist sender.exe" or the seeding systems' automated message system.
 */
export const useBf1seederplayersBf1SeederplayersGet = <TData = Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1seederplayersBf1SeederplayersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1seederplayersBf1SeederplayersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1seederplayersBf1SeederplayersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get id of a player within bf1
 */
export const bf1playerBf1PlayerGet = (
    params?: Bf1playerBf1PlayerGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PersonaInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/player/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1playerBf1PlayerGetQueryKey = (params?: Bf1playerBf1PlayerGetParams,) => {
    return [`https://api.gametools.network/bf1/player/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1playerBf1PlayerGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1playerBf1PlayerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1playerBf1PlayerGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>> = ({ signal }) => bf1playerBf1PlayerGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1playerBf1PlayerGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>>
export type Bf1playerBf1PlayerGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get id of a player within bf1
 */
export const useBf1playerBf1PlayerGet = <TData = Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1playerBf1PlayerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1playerBf1PlayerGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1playerBf1PlayerGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get stats from the given player for bf1
 */
export const bf1statsBf1StatsGet = (
    params?: Bf1statsBf1StatsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteMainStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/stats/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1statsBf1StatsGetQueryKey = (params?: Bf1statsBf1StatsGetParams,) => {
    return [`https://api.gametools.network/bf1/stats/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1statsBf1StatsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1statsBf1StatsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1statsBf1StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1statsBf1StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1statsBf1StatsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1statsBf1StatsGet>>> = ({ signal }) => bf1statsBf1StatsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1statsBf1StatsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1statsBf1StatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1statsBf1StatsGet>>>
export type Bf1statsBf1StatsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get stats from the given player for bf1
 */
export const useBf1statsBf1StatsGet = <TData = Awaited<ReturnType<typeof bf1statsBf1StatsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1statsBf1StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1statsBf1StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1statsBf1StatsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get weapon stats from the given player for bf1
 */
export const bf1weaponsBf1WeaponsGet = (
    params?: Bf1weaponsBf1WeaponsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteWeaponStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/weapons/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1weaponsBf1WeaponsGetQueryKey = (params?: Bf1weaponsBf1WeaponsGetParams,) => {
    return [`https://api.gametools.network/bf1/weapons/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1weaponsBf1WeaponsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1weaponsBf1WeaponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1weaponsBf1WeaponsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>> = ({ signal }) => bf1weaponsBf1WeaponsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1weaponsBf1WeaponsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>>
export type Bf1weaponsBf1WeaponsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get weapon stats from the given player for bf1
 */
export const useBf1weaponsBf1WeaponsGet = <TData = Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1weaponsBf1WeaponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1weaponsBf1WeaponsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1weaponsBf1WeaponsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get vehicle stats from the given player for bf1
 */
export const bf1vehiclesBf1VehiclesGet = (
    params?: Bf1vehiclesBf1VehiclesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteVehicleStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/vehicles/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1vehiclesBf1VehiclesGetQueryKey = (params?: Bf1vehiclesBf1VehiclesGetParams,) => {
    return [`https://api.gametools.network/bf1/vehicles/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1vehiclesBf1VehiclesGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1vehiclesBf1VehiclesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1vehiclesBf1VehiclesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>> = ({ signal }) => bf1vehiclesBf1VehiclesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1vehiclesBf1VehiclesGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>>
export type Bf1vehiclesBf1VehiclesGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get vehicle stats from the given player for bf1
 */
export const useBf1vehiclesBf1VehiclesGet = <TData = Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1vehiclesBf1VehiclesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1vehiclesBf1VehiclesGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1vehiclesBf1VehiclesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get class stats from the given player for bf1
 */
export const bf1classesBf1ClassesGet = (
    params?: Bf1classesBf1ClassesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteClassStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/classes/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1classesBf1ClassesGetQueryKey = (params?: Bf1classesBf1ClassesGetParams,) => {
    return [`https://api.gametools.network/bf1/classes/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1classesBf1ClassesGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1classesBf1ClassesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1classesBf1ClassesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>> = ({ signal }) => bf1classesBf1ClassesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1classesBf1ClassesGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>>
export type Bf1classesBf1ClassesGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get class stats from the given player for bf1
 */
export const useBf1classesBf1ClassesGet = <TData = Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1classesBf1ClassesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1classesBf1ClassesGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1classesBf1ClassesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get all stats for website
 */
export const bf1AllBf1AllGet = (
    params?: Bf1AllBf1AllGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf1Combined>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/all/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1AllBf1AllGetQueryKey = (params?: Bf1AllBf1AllGetParams,) => {
    return [`https://api.gametools.network/bf1/all/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1AllBf1AllGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1AllBf1AllGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1AllBf1AllGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1AllBf1AllGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1AllBf1AllGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1AllBf1AllGet>>> = ({ signal }) => bf1AllBf1AllGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1AllBf1AllGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1AllBf1AllGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1AllBf1AllGet>>>
export type Bf1AllBf1AllGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get all stats for website
 */
export const useBf1AllBf1AllGet = <TData = Awaited<ReturnType<typeof bf1AllBf1AllGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1AllBf1AllGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1AllBf1AllGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1AllBf1AllGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get gamemode stats from the given player for bf1
 */
export const bf1gamemodeBf1GamemodeGet = (
    params?: Bf1gamemodeBf1GamemodeGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GamemodeStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/gamemode/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1gamemodeBf1GamemodeGetQueryKey = (params?: Bf1gamemodeBf1GamemodeGetParams,) => {
    return [`https://api.gametools.network/bf1/gamemode/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1gamemodeBf1GamemodeGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1gamemodeBf1GamemodeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1gamemodeBf1GamemodeGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>> = ({ signal }) => bf1gamemodeBf1GamemodeGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1gamemodeBf1GamemodeGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>>
export type Bf1gamemodeBf1GamemodeGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get gamemode stats from the given player for bf1
 */
export const useBf1gamemodeBf1GamemodeGet = <TData = Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1gamemodeBf1GamemodeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1gamemodeBf1GamemodeGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1gamemodeBf1GamemodeGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get progress of the medals of the given player for bf1
 */
export const bf1progressBf1ProgressGet = (
    params?: Bf1progressBf1ProgressGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProgressStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/progress/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1progressBf1ProgressGetQueryKey = (params?: Bf1progressBf1ProgressGetParams,) => {
    return [`https://api.gametools.network/bf1/progress/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1progressBf1ProgressGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1progressBf1ProgressGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1progressBf1ProgressGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>> = ({ signal }) => bf1progressBf1ProgressGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1progressBf1ProgressGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>>
export type Bf1progressBf1ProgressGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get progress of the medals of the given player for bf1
 */
export const useBf1progressBf1ProgressGet = <TData = Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1progressBf1ProgressGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1progressBf1ProgressGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1progressBf1ProgressGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const statsarrayBf1StatsarrayGet = (
    params?: StatsarrayBf1StatsarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatsArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/statsarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatsarrayBf1StatsarrayGetQueryKey = (params?: StatsarrayBf1StatsarrayGetParams,) => {
    return [`https://api.gametools.network/bf1/statsarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatsarrayBf1StatsarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatsarrayBf1StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsarrayBf1StatsarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>> = ({ signal }) => statsarrayBf1StatsarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsarrayBf1StatsarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>>
export type StatsarrayBf1StatsarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const useStatsarrayBf1StatsarrayGet = <TData = Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatsarrayBf1StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf1StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsarrayBf1StatsarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const printLoggedDataBf1StatusarrayGet = (
    params?: PrintLoggedDataBf1StatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteStatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBf1StatusarrayGetQueryKey = (params?: PrintLoggedDataBf1StatusarrayGetParams,) => {
    return [`https://api.gametools.network/bf1/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBf1StatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBf1StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBf1StatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>> = ({ signal }) => printLoggedDataBf1StatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBf1StatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>>
export type PrintLoggedDataBf1StatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const usePrintLoggedDataBf1StatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBf1StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBf1StatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the servers playeramount over time
 */
export const loggedServerDataBf1ServerarrayGet = (
    params?: LoggedServerDataBf1ServerarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/serverarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLoggedServerDataBf1ServerarrayGetQueryKey = (params?: LoggedServerDataBf1ServerarrayGetParams,) => {
    return [`https://api.gametools.network/bf1/serverarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getLoggedServerDataBf1ServerarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: LoggedServerDataBf1ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoggedServerDataBf1ServerarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>> = ({ signal }) => loggedServerDataBf1ServerarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LoggedServerDataBf1ServerarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>>
export type LoggedServerDataBf1ServerarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the servers playeramount over time
 */
export const useLoggedServerDataBf1ServerarrayGet = <TData = Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: LoggedServerDataBf1ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLoggedServerDataBf1ServerarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * For platform there is pc, xboxone and ps4
 * @summary Get the player- / serveramount for all regions.
 */
export const statusBf1StatusGet = (
    params?: StatusBf1StatusGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteGameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1/status/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatusBf1StatusGetQueryKey = (params?: StatusBf1StatusGetParams,) => {
    return [`https://api.gametools.network/bf1/status/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatusBf1StatusGetQueryOptions = <TData = Awaited<ReturnType<typeof statusBf1StatusGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatusBf1StatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf1StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusBf1StatusGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusBf1StatusGet>>> = ({ signal }) => statusBf1StatusGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusBf1StatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatusBf1StatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusBf1StatusGet>>>
export type StatusBf1StatusGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions.
 */
export const useStatusBf1StatusGet = <TData = Awaited<ReturnType<typeof statusBf1StatusGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatusBf1StatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf1StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatusBf1StatusGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



