/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import type { FrostbitePlatoonInfo } from './frostbitePlatoonInfo';
import type { Bf1CombinedAvatar } from './bf1CombinedAvatar';
import type { FrostbiteClassInfo } from './frostbiteClassInfo';
import type { FrostbiteGamemodeInfo } from './frostbiteGamemodeInfo';
import type { ProgressInfo } from './progressInfo';
import type { PlayerSession } from './playerSession';
import type { Bf1CombinedUserId } from './bf1CombinedUserId';
import type { Bf1CombinedUserName } from './bf1CombinedUserName';
import type { FrostbiteVehicleInfo } from './frostbiteVehicleInfo';
import type { FrostbiteWeaponInfo } from './frostbiteWeaponInfo';

export interface Bf1Combined {
  accuracy: number;
  activePlatoon: FrostbitePlatoonInfo;
  avatar?: Bf1CombinedAvatar;
  avengerKills: number;
  awardScore: number;
  bestClass: number;
  bonusScore: number;
  classes: FrostbiteClassInfo[];
  currentRankProgress: number;
  deaths: number;
  dogtagsTaken: number;
  gamemodes: FrostbiteGamemodeInfo[];
  headshots: number;
  headShots: number;
  heals: number;
  highestKillStreak: number;
  id: number;
  infantryKillDeath: number;
  infantryKillsPerMinute: number;
  killAssists: number;
  killDeath: number;
  kills: number;
  killsPerMinute: number;
  longestHeadShot: number;
  loses: number;
  platoons: FrostbitePlatoonInfo[];
  progress: ProgressInfo[];
  rank: number;
  rankImg: string;
  rankName: string;
  repairs: number;
  revives: number;
  roundsPlayed: number;
  saviorKills: number;
  scorePerMinute: number;
  secondsPlayed: number;
  sessions: PlayerSession[];
  skill: number;
  squadScore: number;
  timePlayed: string;
  totalRankProgress: number;
  userId?: Bf1CombinedUserId;
  userName?: Bf1CombinedUserName;
  vehicles: FrostbiteVehicleInfo[];
  weapons: FrostbiteWeaponInfo[];
  winPercent: number;
  wins: number;
}
