/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */

export type Bf2042serversBf2042ServersGetParams = {
/**
 * searching based on servername
 */
name?: string | null;
/**
 * the name of the experience within portal.battlefield.com.
 */
experiencename?: string | null;
/**
 * The regions available are: all (all regions), eu, asia, nam (north america), sam (south america), afr (Africa) or oc (Oceana).
 */
region?: string;
/**
 * The available maps are: 'Arica Harbor', 'Valparaiso', 'Battle of the Bulge', 'El Alamein', 'Caspian Border', 'Noshahr Canals', 'Orbital', 'Hourglass', 'Kaleidoscope', 'Breakaway', 'Discarded', 'Manifest' and 'Renewal'
 */
maps?: string;
/**
 * The available modes are: 'Breakthrough Large', 'Breakthrough', 'Conquest', 'Custom', 'Rush' and 'Conquest large'
 */
modes?: string;
/**
 * the max amount of servers it will gather, give it a number between 1 and 250.
 */
limit?: number;
/**
 * For platform there is pc, xboxone and ps4, ps5 and xboxseries
 */
platform?: string;
/**
 * If you want to filter out servers with/without a password
 */
has_password?: boolean | null;
/**
 * to filter by serverowner, send a array like this: owners=[{"nucleusid":2800753812,"personaid":794397421,"platformid":1}] or owners=[{"nucleusid":2800753812,"personaid":794397421,"platform":"pc"}] (query formatted ofc)
 */
owners?: string;
};
