/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Bf1942ServersBf1942ServersGetParams,
  Bf1942StatusarrayBf1942StatusarrayGetParams,
  HTTPValidationError,
  LoggedServerDataBf1942ServerarrayGetParams,
  OlderGameStatus,
  OlderTitleSearch,
  StatusArray
} from '.././model'



/**
 * @summary Get a list of servers based on given name
 */
export const bf1942ServersBf1942ServersGet = (
    params: Bf1942ServersBf1942ServersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OlderTitleSearch>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1942/servers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1942ServersBf1942ServersGetQueryKey = (params: Bf1942ServersBf1942ServersGetParams,) => {
    return [`https://api.gametools.network/bf1942/servers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1942ServersBf1942ServersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>, TError = AxiosError<HTTPValidationError>>(params: Bf1942ServersBf1942ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1942ServersBf1942ServersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>> = ({ signal }) => bf1942ServersBf1942ServersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1942ServersBf1942ServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>>
export type Bf1942ServersBf1942ServersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers based on given name
 */
export const useBf1942ServersBf1942ServersGet = <TData = Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bf1942ServersBf1942ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942ServersBf1942ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1942ServersBf1942ServersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const bf1942StatusarrayBf1942StatusarrayGet = (
    params?: Bf1942StatusarrayBf1942StatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1942/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf1942StatusarrayBf1942StatusarrayGetQueryKey = (params?: Bf1942StatusarrayBf1942StatusarrayGetParams,) => {
    return [`https://api.gametools.network/bf1942/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf1942StatusarrayBf1942StatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf1942StatusarrayBf1942StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1942StatusarrayBf1942StatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>> = ({ signal }) => bf1942StatusarrayBf1942StatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1942StatusarrayBf1942StatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>>
export type Bf1942StatusarrayBf1942StatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const useBf1942StatusarrayBf1942StatusarrayGet = <TData = Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf1942StatusarrayBf1942StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942StatusarrayBf1942StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1942StatusarrayBf1942StatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the servers playeramount over time
 */
export const loggedServerDataBf1942ServerarrayGet = (
    params: LoggedServerDataBf1942ServerarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1942/serverarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLoggedServerDataBf1942ServerarrayGetQueryKey = (params: LoggedServerDataBf1942ServerarrayGetParams,) => {
    return [`https://api.gametools.network/bf1942/serverarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getLoggedServerDataBf1942ServerarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(params: LoggedServerDataBf1942ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoggedServerDataBf1942ServerarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>> = ({ signal }) => loggedServerDataBf1942ServerarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LoggedServerDataBf1942ServerarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>>
export type LoggedServerDataBf1942ServerarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the servers playeramount over time
 */
export const useLoggedServerDataBf1942ServerarrayGet = <TData = Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params: LoggedServerDataBf1942ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf1942ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLoggedServerDataBf1942ServerarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions.
 */
export const bf1942statusBf1942StatusGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OlderGameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1942/status/`,options
    );
  }


export const getBf1942statusBf1942StatusGetQueryKey = () => {
    return [`https://api.gametools.network/bf1942/status/`] as const;
    }

    
export const getBf1942statusBf1942StatusGetQueryOptions = <TData = Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf1942statusBf1942StatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>> = ({ signal }) => bf1942statusBf1942StatusGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf1942statusBf1942StatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>>
export type Bf1942statusBf1942StatusGetQueryError = AxiosError<unknown>

/**
 * @summary Get the player- / serveramount for all regions.
 */
export const useBf1942statusBf1942StatusGet = <TData = Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf1942statusBf1942StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf1942statusBf1942StatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



