/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  FrostbiteGameStatus,
  FrostbiteStatusArray
} from '.././model'

export const getPrintLoggedDataBf1MarneStatusarrayGetMock = (overrideResponse: any = {}): FrostbiteStatusArray => ({communitySoldierAmount: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), diceSoldierAmount: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), endTime: faker.word.sample(), soldierAmount: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), startTime: faker.word.sample(), timeStamps: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), ...overrideResponse})

export const getStatusBf1MarneStatusGetMock = (overrideResponse: any = {}): FrostbiteGameStatus => ({regions: {
        [faker.string.alphanumeric(5)]: {amounts: {queueAmount: faker.number.int({min: undefined, max: undefined}), serverAmount: faker.number.int({min: undefined, max: undefined}), soldierAmount: faker.number.int({min: undefined, max: undefined}), spectatorAmount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse}, region: faker.word.sample(), regionName: faker.word.sample(), ...overrideResponse}
      }, ...overrideResponse})


export const getPrintLoggedDataBf1MarneStatusarrayGetMockHandler = (overrideResponse?: FrostbiteStatusArray) => {
  return http.get('*/bf1_marne/statusarray/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getPrintLoggedDataBf1MarneStatusarrayGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getStatusBf1MarneStatusGetMockHandler = (overrideResponse?: FrostbiteGameStatus) => {
  return http.get('*/bf1_marne/status/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getStatusBf1MarneStatusGetMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getBattlefield1MarneMock = () => [
  getPrintLoggedDataBf1MarneStatusarrayGetMockHandler(),
  getStatusBf1MarneStatusGetMockHandler()
]
