/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  FrostbiteGameStatus,
  FrostbiteStatusArray,
  HTTPValidationError,
  PrintLoggedDataBf1MarneStatusarrayGetParams,
  StatusBf1MarneStatusGetParams
} from '.././model'



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const printLoggedDataBf1MarneStatusarrayGet = (
    params?: PrintLoggedDataBf1MarneStatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteStatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1_marne/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBf1MarneStatusarrayGetQueryKey = (params?: PrintLoggedDataBf1MarneStatusarrayGetParams,) => {
    return [`https://api.gametools.network/bf1_marne/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBf1MarneStatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBf1MarneStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBf1MarneStatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>> = ({ signal }) => printLoggedDataBf1MarneStatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBf1MarneStatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>>
export type PrintLoggedDataBf1MarneStatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const usePrintLoggedDataBf1MarneStatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBf1MarneStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf1MarneStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBf1MarneStatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * For platform there is pc, xboxone and ps4
 * @summary Get the player- / serveramount for all regions.
 */
export const statusBf1MarneStatusGet = (
    params?: StatusBf1MarneStatusGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteGameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bf1_marne/status/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatusBf1MarneStatusGetQueryKey = (params?: StatusBf1MarneStatusGetParams,) => {
    return [`https://api.gametools.network/bf1_marne/status/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatusBf1MarneStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof statusBf1MarneStatusGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatusBf1MarneStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf1MarneStatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusBf1MarneStatusGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusBf1MarneStatusGet>>> = ({ signal }) => statusBf1MarneStatusGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusBf1MarneStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatusBf1MarneStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusBf1MarneStatusGet>>>
export type StatusBf1MarneStatusGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions.
 */
export const useStatusBf1MarneStatusGet = <TData = Awaited<ReturnType<typeof statusBf1MarneStatusGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatusBf1MarneStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf1MarneStatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatusBf1MarneStatusGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



