/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BattlelogVehicleStats,
  BattlelogWeaponStats,
  Bf4AllBf4AllGetParams,
  Bf4Combined,
  Bf4DetailedServerInfo,
  Bf4Search,
  Bf4detailedserverBf4DetailedserverGetParams,
  Bf4serversBf4ServersGetParams,
  Bf4statsBf4StatsGetParams,
  Bf4vehiclesBf4VehiclesGetParams,
  Bf4weaponsBf4WeaponsGetParams,
  FrostbiteMainStats,
  GameStatus,
  HTTPValidationError,
  LoggedServerDataBf4ServerarrayGetParams,
  PrintLoggedDataBf4StatusarrayGetParams,
  StatsArray,
  StatsarrayBf4StatsarrayGetParams,
  StatusArray,
  StatusBf4StatusGetParams
} from '.././model'



/**
 * The regions available are: all (all regions), eu, asia, nam (north america), sam (south america), au (Australia) or oc (Oceana).
                    For platform there is pc, xboxone and ps4 (cache of 10 seconds)
                    Limit is the max amount of servers it will gather, give it a number between 1 and 100.
                    For player filter you can use oneToFive, sixToTen, tenPlus or none, comma seperated list is also a option example: "&player_filters=onetofive,sixtoten" to filter on the amount of free slots.
                    Same for gamemode filter as with player filter but with the name of the gamemode
 * @summary Get a list of servers based on given name
 */
export const bf4serversBf4ServersGet = (
    params: Bf4serversBf4ServersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf4Search>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/servers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4serversBf4ServersGetQueryKey = (params: Bf4serversBf4ServersGetParams,) => {
    return [`https://api.gametools.network/bf4/servers/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4serversBf4ServersGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4serversBf4ServersGet>>, TError = AxiosError<HTTPValidationError>>(params: Bf4serversBf4ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4serversBf4ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4serversBf4ServersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4serversBf4ServersGet>>> = ({ signal }) => bf4serversBf4ServersGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4serversBf4ServersGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4serversBf4ServersGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4serversBf4ServersGet>>>
export type Bf4serversBf4ServersGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get a list of servers based on given name
 */
export const useBf4serversBf4ServersGet = <TData = Awaited<ReturnType<typeof bf4serversBf4ServersGet>>, TError = AxiosError<HTTPValidationError>>(
 params: Bf4serversBf4ServersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4serversBf4ServersGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4serversBf4ServersGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * For platform there is pc, xboxone and ps4. players is only for pc (has longer cache, 1 mins)
 * @summary Get detailed info about 1 server
 */
export const bf4detailedserverBf4DetailedserverGet = (
    params?: Bf4detailedserverBf4DetailedserverGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf4DetailedServerInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/detailedserver/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4detailedserverBf4DetailedserverGetQueryKey = (params?: Bf4detailedserverBf4DetailedserverGetParams,) => {
    return [`https://api.gametools.network/bf4/detailedserver/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4detailedserverBf4DetailedserverGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf4detailedserverBf4DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4detailedserverBf4DetailedserverGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>> = ({ signal }) => bf4detailedserverBf4DetailedserverGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4detailedserverBf4DetailedserverGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>>
export type Bf4detailedserverBf4DetailedserverGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get detailed info about 1 server
 */
export const useBf4detailedserverBf4DetailedserverGet = <TData = Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf4detailedserverBf4DetailedserverGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4detailedserverBf4DetailedserverGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4detailedserverBf4DetailedserverGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Available options for platform: pc, ps3, ps4, xbox360, xboxone.

for nametypes you only have to fill in one of them: name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur&platform=pc
 * @summary Get stats from the given player for bf4
 */
export const bf4statsBf4StatsGet = (
    params?: Bf4statsBf4StatsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FrostbiteMainStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/stats/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4statsBf4StatsGetQueryKey = (params?: Bf4statsBf4StatsGetParams,) => {
    return [`https://api.gametools.network/bf4/stats/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4statsBf4StatsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4statsBf4StatsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf4statsBf4StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4statsBf4StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4statsBf4StatsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4statsBf4StatsGet>>> = ({ signal }) => bf4statsBf4StatsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4statsBf4StatsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4statsBf4StatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4statsBf4StatsGet>>>
export type Bf4statsBf4StatsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get stats from the given player for bf4
 */
export const useBf4statsBf4StatsGet = <TData = Awaited<ReturnType<typeof bf4statsBf4StatsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf4statsBf4StatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4statsBf4StatsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4statsBf4StatsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Available options for platform: pc, ps3, ps4, xbox360, xboxone.

for nametypes you only have to fill in one of them: name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur&platform=pc
 * @summary Get weapon stats from the given player for bf4
 */
export const bf4weaponsBf4WeaponsGet = (
    params?: Bf4weaponsBf4WeaponsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BattlelogWeaponStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/weapons/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4weaponsBf4WeaponsGetQueryKey = (params?: Bf4weaponsBf4WeaponsGetParams,) => {
    return [`https://api.gametools.network/bf4/weapons/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4weaponsBf4WeaponsGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf4weaponsBf4WeaponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4weaponsBf4WeaponsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>> = ({ signal }) => bf4weaponsBf4WeaponsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4weaponsBf4WeaponsGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>>
export type Bf4weaponsBf4WeaponsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get weapon stats from the given player for bf4
 */
export const useBf4weaponsBf4WeaponsGet = <TData = Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf4weaponsBf4WeaponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4weaponsBf4WeaponsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4weaponsBf4WeaponsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Available options for platform: pc, ps3, ps4, xbox360, xboxone.

for nametypes you only have to fill in one of them: name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur&platform=pc
 * @summary Get weapon stats from the given player for bf4
 */
export const bf4vehiclesBf4VehiclesGet = (
    params?: Bf4vehiclesBf4VehiclesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BattlelogVehicleStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/vehicles/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4vehiclesBf4VehiclesGetQueryKey = (params?: Bf4vehiclesBf4VehiclesGetParams,) => {
    return [`https://api.gametools.network/bf4/vehicles/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4vehiclesBf4VehiclesGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf4vehiclesBf4VehiclesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4vehiclesBf4VehiclesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>> = ({ signal }) => bf4vehiclesBf4VehiclesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4vehiclesBf4VehiclesGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>>
export type Bf4vehiclesBf4VehiclesGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get weapon stats from the given player for bf4
 */
export const useBf4vehiclesBf4VehiclesGet = <TData = Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf4vehiclesBf4VehiclesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4vehiclesBf4VehiclesGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4vehiclesBf4VehiclesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Available options for platform: pc, ps3, ps4, xbox360, xboxone.

for nametypes you only have to fill in one of them: name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur&platform=pc
 * @summary Get all stats for website
 */
export const bf4AllBf4AllGet = (
    params?: Bf4AllBf4AllGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bf4Combined>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/all/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBf4AllBf4AllGetQueryKey = (params?: Bf4AllBf4AllGetParams,) => {
    return [`https://api.gametools.network/bf4/all/`, ...(params ? [params]: [])] as const;
    }

    
export const getBf4AllBf4AllGetQueryOptions = <TData = Awaited<ReturnType<typeof bf4AllBf4AllGet>>, TError = AxiosError<HTTPValidationError>>(params?: Bf4AllBf4AllGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4AllBf4AllGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBf4AllBf4AllGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bf4AllBf4AllGet>>> = ({ signal }) => bf4AllBf4AllGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bf4AllBf4AllGet>>, TError, TData> & { queryKey: QueryKey }
}

export type Bf4AllBf4AllGetQueryResult = NonNullable<Awaited<ReturnType<typeof bf4AllBf4AllGet>>>
export type Bf4AllBf4AllGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get all stats for website
 */
export const useBf4AllBf4AllGet = <TData = Awaited<ReturnType<typeof bf4AllBf4AllGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: Bf4AllBf4AllGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bf4AllBf4AllGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBf4AllBf4AllGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const statsarrayBf4StatsarrayGet = (
    params?: StatsarrayBf4StatsarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatsArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/statsarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatsarrayBf4StatsarrayGetQueryKey = (params?: StatsarrayBf4StatsarrayGetParams,) => {
    return [`https://api.gametools.network/bf4/statsarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatsarrayBf4StatsarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatsarrayBf4StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsarrayBf4StatsarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>> = ({ signal }) => statsarrayBf4StatsarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsarrayBf4StatsarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>>
export type StatsarrayBf4StatsarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get changes in players' stats over time, this gets saved every time you use the standard stats command in the api or gamestats bot (stats are per day, max 1 month)
 */
export const useStatsarrayBf4StatsarrayGet = <TData = Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatsarrayBf4StatsarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsarrayBf4StatsarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsarrayBf4StatsarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Possible regions are: "ALL", "EU", "Asia", "NAm", "SAm", "AU" and "OC".
            For platform there is "pc", "xboxone", "ps4" and "all"
            For type: "amounts", "maps" (serveramount) and "modes" (serveramount)
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const printLoggedDataBf4StatusarrayGet = (
    params?: PrintLoggedDataBf4StatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBf4StatusarrayGetQueryKey = (params?: PrintLoggedDataBf4StatusarrayGetParams,) => {
    return [`https://api.gametools.network/bf4/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBf4StatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBf4StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBf4StatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>> = ({ signal }) => printLoggedDataBf4StatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBf4StatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>>
export type PrintLoggedDataBf4StatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const usePrintLoggedDataBf4StatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBf4StatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBf4StatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBf4StatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the servers playeramount over time
 */
export const loggedServerDataBf4ServerarrayGet = (
    params?: LoggedServerDataBf4ServerarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/serverarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLoggedServerDataBf4ServerarrayGetQueryKey = (params?: LoggedServerDataBf4ServerarrayGetParams,) => {
    return [`https://api.gametools.network/bf4/serverarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getLoggedServerDataBf4ServerarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: LoggedServerDataBf4ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoggedServerDataBf4ServerarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>> = ({ signal }) => loggedServerDataBf4ServerarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LoggedServerDataBf4ServerarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>>
export type LoggedServerDataBf4ServerarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the servers playeramount over time
 */
export const useLoggedServerDataBf4ServerarrayGet = <TData = Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: LoggedServerDataBf4ServerarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loggedServerDataBf4ServerarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLoggedServerDataBf4ServerarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions.
 */
export const statusBf4StatusGet = (
    params?: StatusBf4StatusGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameStatus>> => {
    
    return axios.get(
      `https://api.gametools.network/bf4/status/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getStatusBf4StatusGetQueryKey = (params?: StatusBf4StatusGetParams,) => {
    return [`https://api.gametools.network/bf4/status/`, ...(params ? [params]: [])] as const;
    }

    
export const getStatusBf4StatusGetQueryOptions = <TData = Awaited<ReturnType<typeof statusBf4StatusGet>>, TError = AxiosError<HTTPValidationError>>(params?: StatusBf4StatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf4StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusBf4StatusGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusBf4StatusGet>>> = ({ signal }) => statusBf4StatusGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusBf4StatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type StatusBf4StatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusBf4StatusGet>>>
export type StatusBf4StatusGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions.
 */
export const useStatusBf4StatusGet = <TData = Awaited<ReturnType<typeof statusBf4StatusGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: StatusBf4StatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusBf4StatusGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatusBf4StatusGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



