/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Stats API for the Battlefield series
 * This project also has a <a href="https://top.gg/bot/714524944783900794" target="_blank">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href="https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html" target="_blank">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href="https://www.bf2hub.com" target="_blank">BF2Hub</a> and <a href="https://playbf2.tilda.ws/en" target="_blank">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href="https://battlefield2142.co/" target="_blank">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href="https://discord.gg/zMuxW6c" target="_blank">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href="https://github.com/sponsors/community-network" target="_blank">becoming a sponsor on GitHub</a>.
 * OpenAPI spec version: 1.3.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BfgamesBfglobalGamesGetParams,
  DetailedPlatoonInfo,
  GlobalStatusArray,
  HTTPValidationError,
  PlatoonStats,
  PlatoonstatBfglobalDetailedplatoonGetParams,
  PlayerGames,
  PrintLoggedDataBfglobalStatusarrayGetParams,
  SearchPlatoonBfglobalPlatoonsGetParams,
  TotalStatusArray,
  TotalStatusArrayBfglobalTotalstatusarrayGetParams
} from '.././model'



/**
 * you only have to fill in one of them: oid (used in bfban: 'https://bfban.com/#/cheaters/1008084550936'), name (normal playername), or playerid (same as id in what it returns - fastest method).

if you dont know what you need to use, just use 'name', just fill the playername in there: **\/stats/?name=iiTzArcur
 * @summary Get the games a user has
 */
export const bfgamesBfglobalGamesGet = (
    params?: BfgamesBfglobalGamesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerGames>> => {
    
    return axios.get(
      `https://api.gametools.network/bfglobal/games/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getBfgamesBfglobalGamesGetQueryKey = (params?: BfgamesBfglobalGamesGetParams,) => {
    return [`https://api.gametools.network/bfglobal/games/`, ...(params ? [params]: [])] as const;
    }

    
export const getBfgamesBfglobalGamesGetQueryOptions = <TData = Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>, TError = AxiosError<HTTPValidationError>>(params?: BfgamesBfglobalGamesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBfgamesBfglobalGamesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>> = ({ signal }) => bfgamesBfglobalGamesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type BfgamesBfglobalGamesGetQueryResult = NonNullable<Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>>
export type BfgamesBfglobalGamesGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the games a user has
 */
export const useBfgamesBfglobalGamesGet = <TData = Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: BfgamesBfglobalGamesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bfgamesBfglobalGamesGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getBfgamesBfglobalGamesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const printLoggedDataBfglobalStatusarrayGet = (
    params?: PrintLoggedDataBfglobalStatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GlobalStatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bfglobal/statusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPrintLoggedDataBfglobalStatusarrayGetQueryKey = (params?: PrintLoggedDataBfglobalStatusarrayGetParams,) => {
    return [`https://api.gametools.network/bfglobal/statusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getPrintLoggedDataBfglobalStatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: PrintLoggedDataBfglobalStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrintLoggedDataBfglobalStatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>> = ({ signal }) => printLoggedDataBfglobalStatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PrintLoggedDataBfglobalStatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>>
export type PrintLoggedDataBfglobalStatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get the player- / serveramount for all regions from database gathered every hour.
 */
export const usePrintLoggedDataBfglobalStatusarrayGet = <TData = Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: PrintLoggedDataBfglobalStatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof printLoggedDataBfglobalStatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPrintLoggedDataBfglobalStatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Total server and playeramount for all games combined
 */
export const totalStatusArrayBfglobalTotalstatusarrayGet = (
    params?: TotalStatusArrayBfglobalTotalstatusarrayGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TotalStatusArray>> => {
    
    return axios.get(
      `https://api.gametools.network/bfglobal/totalstatusarray/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getTotalStatusArrayBfglobalTotalstatusarrayGetQueryKey = (params?: TotalStatusArrayBfglobalTotalstatusarrayGetParams,) => {
    return [`https://api.gametools.network/bfglobal/totalstatusarray/`, ...(params ? [params]: [])] as const;
    }

    
export const getTotalStatusArrayBfglobalTotalstatusarrayGetQueryOptions = <TData = Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(params?: TotalStatusArrayBfglobalTotalstatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTotalStatusArrayBfglobalTotalstatusarrayGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>> = ({ signal }) => totalStatusArrayBfglobalTotalstatusarrayGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>, TError, TData> & { queryKey: QueryKey }
}

export type TotalStatusArrayBfglobalTotalstatusarrayGetQueryResult = NonNullable<Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>>
export type TotalStatusArrayBfglobalTotalstatusarrayGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Total server and playeramount for all games combined
 */
export const useTotalStatusArrayBfglobalTotalstatusarrayGet = <TData = Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: TotalStatusArrayBfglobalTotalstatusarrayGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totalStatusArrayBfglobalTotalstatusarrayGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getTotalStatusArrayBfglobalTotalstatusarrayGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * It needs a minimum of 3 characters to start the search
                        
Available options for platform: pc, ps4, xboxone.
 * @summary Search for a platoon
 */
export const searchPlatoonBfglobalPlatoonsGet = (
    params: SearchPlatoonBfglobalPlatoonsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlatoonStats>> => {
    
    return axios.get(
      `https://api.gametools.network/bfglobal/platoons/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getSearchPlatoonBfglobalPlatoonsGetQueryKey = (params: SearchPlatoonBfglobalPlatoonsGetParams,) => {
    return [`https://api.gametools.network/bfglobal/platoons/`, ...(params ? [params]: [])] as const;
    }

    
export const getSearchPlatoonBfglobalPlatoonsGetQueryOptions = <TData = Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>, TError = AxiosError<HTTPValidationError>>(params: SearchPlatoonBfglobalPlatoonsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPlatoonBfglobalPlatoonsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>> = ({ signal }) => searchPlatoonBfglobalPlatoonsGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type SearchPlatoonBfglobalPlatoonsGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>>
export type SearchPlatoonBfglobalPlatoonsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Search for a platoon
 */
export const useSearchPlatoonBfglobalPlatoonsGet = <TData = Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>, TError = AxiosError<HTTPValidationError>>(
 params: SearchPlatoonBfglobalPlatoonsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPlatoonBfglobalPlatoonsGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getSearchPlatoonBfglobalPlatoonsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get info about the given platoon
 */
export const platoonstatBfglobalDetailedplatoonGet = (
    params: PlatoonstatBfglobalDetailedplatoonGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetailedPlatoonInfo>> => {
    
    return axios.get(
      `https://api.gametools.network/bfglobal/detailedplatoon/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPlatoonstatBfglobalDetailedplatoonGetQueryKey = (params: PlatoonstatBfglobalDetailedplatoonGetParams,) => {
    return [`https://api.gametools.network/bfglobal/detailedplatoon/`, ...(params ? [params]: [])] as const;
    }

    
export const getPlatoonstatBfglobalDetailedplatoonGetQueryOptions = <TData = Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>, TError = AxiosError<HTTPValidationError>>(params: PlatoonstatBfglobalDetailedplatoonGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlatoonstatBfglobalDetailedplatoonGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>> = ({ signal }) => platoonstatBfglobalDetailedplatoonGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PlatoonstatBfglobalDetailedplatoonGetQueryResult = NonNullable<Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>>
export type PlatoonstatBfglobalDetailedplatoonGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get info about the given platoon
 */
export const usePlatoonstatBfglobalDetailedplatoonGet = <TData = Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>, TError = AxiosError<HTTPValidationError>>(
 params: PlatoonstatBfglobalDetailedplatoonGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platoonstatBfglobalDetailedplatoonGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getPlatoonstatBfglobalDetailedplatoonGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



